export default [
  {
    id: 1,
    title: "HOTEL AL AREBIRA",
    price: 136,
    coverImg: "card_image.png",
    stats: {
      rating: 5.0,
      reviewCount: 6,
    },
    location: "Online",
    openSpots: 0,
  },
  {
    id: 2,
    title: "AL DAAZ",
    price: 125,
    coverImg: "card_image_1.png",
    stats: {
      rating: 5.0,
      reviewCount: 30,
    },
    location: "Online",
    openSpots: 27,
  },
  {
    id: 3,
    title: "KRISHNA SAGAR",
    price: 50,
    coverImg: "card_image_2.png",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 3,
  },
  {
    id: 4,
    title: "MEENAKSHI HOTEL",
    price: 50,
    coverImg: "card_image_4.png",
    stats: {
      rating: 4,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 123,
  },
  {
    id: 5,
    title: "SHIVAJI HOTEL",
    price: 50,
    coverImg: "card_image_5.png",
    stats: {
      rating: 4.8,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 10,
  },
  {
    id: 6,
    title: "SOWPARNIKA HOTEL",
    price: 50,
    coverImg: "card_image_2.png",
    stats: {
      rating: 3.7,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 13,
  },
  {
    id: 7,
    title: "SOWPARNIKA HOTEL",
    price: 50,
    coverImg: "card_image.png",
    stats: {
      rating: 5,
      reviewCount: 2,
    },
    location: "Norway",
    openSpots: 12,
  },
];
